---
- name: Create Server Directory
  register: create_server_dir
  file:
    path: "{{ destination_folder }}"
    state: directory
    mode: '0755'

- name: Download server package
  unarchive:
    src: "{{ server_package_url }}"
    dest: "{{ destination_folder }}"
    creates: "{{ destination_folder }}/ServerStart.sh"
    remote_src: yes

- name: Agree to EULA
  template:
    src: './eula.txt'
    dest: "{{ destination_folder }}/eula.txt"

- name: Check running Tmux sessions
  command: tmux ls
  register: tmux_sessions
  failed_when: '"No such" in tmux_sessions.stdout'
  changed_when: '"minecraft-server" not in tmux_sessions.stdout'

- name: Start tmux session with server
  shell: 
    cmd: "tmux new-session -d -s minecraft-server 'chmod a+x ./ServerStart.sh && ./ServerStart.sh'"
    chdir: "{{ destination_folder }}"
  when: '"minecraft-server" not in tmux_sessions.stdout'

- name: Upload server backup script
  template:
    src: './backup.sh'
    dest: "/home/minecraft/backup.sh"

- name: Run backup script
  cron:
    name: 'app backup'
    minute: '0'
    user: root
    job: '/home/minecraft/backup.sh'

