---

- name: Primary Minecraft Server
  hosts: app
  user: jamesapple
  roles:
    - java-base
    - role: gcp-disk
      vars:
        disk_name: google-app-server
        mount_path: "/home/minecraft"
    - role: minecraft-server
      become: True
      vars:
        server_package_url: 'https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2690320/download'
        destination_folder: '/home/minecraft/server'
        config_folder: '/home/minecraft/server-config'
        server_tmux_session_name: 'minecraft-server'

